# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 70295ff431fd48f992a89b546006f46bc2fe4bc6083e2ac1a5609ff35df46a1c7769843da45e9513e7e338d47ec0e4328b08fe5111bb33651adf607a5401deb3

test:
  secret_key_base: 874243c17c11ff9b43e115ebce4103a270f5a7905d229f99583a3a1bf1af88d3bacd6c79ce9143004590f31fd0f2bfc72eb2e195f95cb62967a5a69c00f01908

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
